[versions]
ksp = "2.2.0-2.0.2"
maven-publish = "0.34.0"

[libraries]
# Common
ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-gradle-plugin", version.ref = "ksp" }

[plugins]
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }